name: "Pull Request Labeler"
on:
  - pull_request_target

jobs:
  triage:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/labeler@v3
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
      - name: <DEBUG> Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
        shell: bash
      - uses: eruizalo/github-action-todo-commenter@feat/12-pull_request_target
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          ignore-pattern: '.js$|.snap$'
          review-message: "There are some TODOs to fix. Please take a look :eyes:"
          tags: "TODO,@todo"
