name: Sample Conditional Matrix Build

on: push

jobs:
  matrix_prep:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2

      - id: set-matrix
        uses: JoshuaTheMiller/conditional-build-matrix@main
        with:
          # The simple branch name can be used in the filter now!
          filter: '[]'
  build:
    needs: matrix_prep
    strategy:
      matrix: ${{fromJson(needs.matrix_prep.outputs.matrix)}}
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "${{ matrix.spark }} ${{ matrix.scope }}"
